#!/usr/bin/env python3
"""The two September 2026 additions, recomputed from the released JSONL.

Nothing in the manuscript's new sections is typed by hand. Everything this
script prints is also written to paper/numbers_new.tex as a macro, so the prose
cannot drift from the files in data/.

WHAT IT COVERS

1. THE HEADROOM TEST (data/headroom_test.jsonl). Four arms, order permuted per
   pass: A = 16 threads on logical processors 0-15 with nothing else running,
   B = the same 16 threads with four spinners pinned to processors 16-19 so the
   spare processors are occupied, C = 20 threads on all twenty, D = A again as a
   drift check. The paper previously guessed that headroom was the mechanism and
   said so. If B's spread tracks C's rather than A's, occupying the spare
   processors reproduces the tail and headroom is the mechanism. If B tracks A,
   the guess was wrong. The script reports the arm statistics and states which.

2. THE 7B SIZE-SCALING SWEEP (data/randomized_sweep_7b.jsonl), against the 0.5B
   sweep (data/randomized_sweep.jsonl) measured under the identical protocol.

   THE MACHINE STALLED DURING THE 7B RUN, and the contaminated cells have to
   come out before anything is computed from them. The exclusion rule is:

       drop a cell whose wall-clock duration exceeds twice the MEDIAN DURATION
       FOR ITS OWN THREAD COUNT

   Duration is the gap between consecutive read_at timestamps once the cells are
   sorted by pass then position_in_pass, so it includes the fixed cooldown. The
   per-thread-count reference is not a refinement, it is the whole rule: a
   single-thread cell legitimately takes about four minutes because decode at
   one thread is slow, so any fixed threshold either keeps a contaminated t=1
   cell or throws away clean cells at every other thread count.

   The rule is applied before any statistic is computed, and the same function
   is imported by code/gen_fig_threads.py so the figure and the tables cannot
   disagree.

   The first cell of the run has no predecessor and therefore no derivable
   duration. It is kept, and the script says so rather than silently dropping
   or silently keeping it.
"""
import collections
import json
import os
import statistics as st

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(HERE, "data")
HEADROOM = os.path.join(DATA, "headroom_test.jsonl")
RAND05 = os.path.join(DATA, "randomized_sweep.jsonl")
RAND7B = os.path.join(DATA, "randomized_sweep_7b.jsonl")
OUT = os.path.join(HERE, "paper", "numbers_new.tex")

BW_CEILING_GBS = 53.9        # measured once with a separate probe; see data/README.md
DURATION_FACTOR = 2.0        # "twice the median duration for its own thread count"

lines = ["% generated by code/analyze_headroom_sizes.py -- do not edit"]


def put(name, val):
    lines.append(r"\newcommand{\np%s}{%s}" % (name, val))


def pct(vals, p):
    s = sorted(vals)
    if not s:
        return float("nan")
    k = (len(s) - 1) * p / 100.0
    lo, hi = int(k), min(int(k) + 1, len(s) - 1)
    return s[lo] + (s[hi] - s[lo]) * (k - lo)


def cv(vals):
    return 100.0 * st.pstdev(vals) / st.mean(vals)


def load(path):
    return [json.loads(l) for l in open(path) if l.strip()]


# --------------------------------------------------------------------------
# The exclusion rule. Exported, because gen_fig_threads.py imports it.
# --------------------------------------------------------------------------
def _hms(s):
    h, m, sec = (int(x) for x in s.split(":"))
    return h * 3600 + m * 60 + sec


def cell_durations(rows):
    """Seconds between consecutive cells, in run order (pass, position).

    Returns {(pass, position): seconds}, with the first cell of the run absent
    because it has no predecessor.
    """
    seen = {}
    for r in rows:
        if "error" in r:
            continue
        seen.setdefault((r["pass"], r["position_in_pass"]),
                        (_hms(r["read_at"]), r["threads"]))
    out, prev = {}, None
    for k in sorted(seen):
        t = seen[k][0]
        if prev is not None:
            out[k] = (t - prev) % 86400          # the run can cross midnight
        prev = t
    return out


def stall_excluded(rows, factor=DURATION_FACTOR):
    """The set of (pass, position) cells to drop, and the per-thread thresholds.

    A cell is dropped when its duration exceeds `factor` times the median
    duration of the cells at its own thread count. Cells with no derivable
    duration (the first of the run) are kept.
    """
    dur = cell_durations(rows)
    threads = {}
    for r in rows:
        if "error" not in r:
            threads[(r["pass"], r["position_in_pass"])] = r["threads"]
    by_t = collections.defaultdict(list)
    for k, d in dur.items():
        by_t[threads[k]].append(d)
    thresh = {t: factor * st.median(v) for t, v in by_t.items()}
    drop = {k for k, d in dur.items() if d > thresh[threads[k]]}
    return drop, thresh, dur, threads


def clean_decode(path):
    """Decode rows of a randomised sweep with stall-contaminated cells removed."""
    rows = load(path)
    drop, thresh, dur, threads = stall_excluded(rows)
    keep = [r for r in rows
            if r.get("phase") == "decode" and "error" not in r
            and (r["pass"], r["position_in_pass"]) not in drop]
    return keep, drop, thresh, dur, threads, rows


def main():
    # --------------------------------------------------------------------------
    # 1. The headroom test
    # --------------------------------------------------------------------------
    print("=" * 72)
    print("1. HEADROOM TEST  (data/headroom_test.jsonl)")
    print("=" * 72)
    hr = load(HEADROOM)
    hdec = collections.defaultdict(list)
    hcells = collections.Counter()
    for r in hr:
        if r.get("phase") != "decode" or "error" in r:
            continue
        hdec[r["arm"]].extend(r["samples_ts"])
        hcells[r["arm"]] += 1

    print("\n%-14s %4s %6s %8s %8s %8s %8s %7s" %
          ("arm", "n", "cells", "median", "p25", "p75", "min", "CV%"))
    for a in sorted(hdec):
        v = hdec[a]
        print("%-14s %4d %6d %8.1f %8.1f %8.1f %8.1f %7.1f" %
              (a, len(v), hcells[a], st.median(v), pct(v, 25), pct(v, 75),
               min(v), cv(v)))

    A, B, C, D = (hdec["A_16_free"], hdec["B_16_loaded"],
                  hdec["C_20_free"], hdec["D_16_repeat"])
    cvA, cvB, cvC, cvD = cv(A), cv(B), cv(C), cv(D)

    # Which of A and C does B sit nearer to, on the spread that is the finding?
    near_C = abs(cvB - cvC) < abs(cvB - cvA)
    print("\nCV: A(16 free) %.1f%%  B(16 loaded) %.1f%%  C(20 free) %.1f%%  "
          "D(16 repeat) %.1f%%" % (cvA, cvB, cvC, cvD))
    print("B is nearer %s  (|B-A| = %.1f pp, |B-C| = %.1f pp)"
          % ("C, the oversubscribed arm" if near_C else "A, the baseline",
             abs(cvB - cvA), abs(cvB - cvC)))
    print("drift check: D against A, CV %.1f%% vs %.1f%%, median %.1f vs %.1f"
          % (cvD, cvA, st.median(D), st.median(A)))
    print("VERDICT: %s" % ("occupying the spare processors REPRODUCES the tail; "
                           "headroom is the mechanism" if near_C else
                           "occupying the spare processors does NOT reproduce the "
                           "tail; the headroom account is wrong"))

    put("HrPasses", str(len({r["pass"] for r in hr if "pass" in r})))
    put("HrReps", str(max(r.get("reps", 0) for r in hr)))
    put("HrN", str(len(A)))
    for nm, v in (("A", A), ("B", B), ("C", C), ("D", D)):
        put("Hr%sMed" % nm, "%.1f" % st.median(v))
        put("Hr%sPTwentyFive" % nm, "%.1f" % pct(v, 25))
        put("Hr%sMin" % nm, "%.1f" % min(v))
        put("Hr%sCV" % nm, "%.1f" % cv(v))
    put("HrNearer", "C" if near_C else "A")
    put("HrBvsA", "%.1f" % abs(cvB - cvA))
    put("HrBvsC", "%.1f" % abs(cvB - cvC))
    put("HrBWorstOfA", "%.0f" % (100 * min(B) / st.median(A)))
    put("HrCWorstOfA", "%.0f" % (100 * min(C) / st.median(A)))
    put("HrAWorstOfA", "%.0f" % (100 * min(A) / st.median(A)))
    put("HrDDriftPct", "%.1f" % (100 * abs(st.median(D) / st.median(A) - 1)))
    rows = []
    LBL = {"A_16_free": "A: 16 threads, 4 processors free",
           "B_16_loaded": "B: 16 threads, 4 processors occupied",
           "C_20_free": "C: 20 threads, 0 processors free",
           "D_16_repeat": "D: A repeated (drift check)"}
    for a in ("A_16_free", "B_16_loaded", "C_20_free", "D_16_repeat"):
        v = hdec[a]
        rows.append("%s & %.1f & %.1f & %.1f & %.1f \\\\"
                    % (LBL[a], st.median(v), pct(v, 25), min(v), cv(v)))
    put("TableHeadroom", "%\n" + "\n".join(rows))


    # --------------------------------------------------------------------------
    # 2. The 7B sweep, after the stall exclusion
    # --------------------------------------------------------------------------
    print()
    print("=" * 72)
    print("2. 7B SWEEP  (data/randomized_sweep_7b.jsonl)")
    print("=" * 72)
    keep7, drop7, thresh7, dur7, thr7, all7 = clean_decode(RAND7B)
    cells_total = len({(r["pass"], r["position_in_pass"]) for r in all7
                       if "error" not in r})
    print("\ncells in file %d, excluded %d, kept %d"
          % (cells_total, len(drop7), cells_total - len(drop7)))
    print("first cell of the run has no predecessor and is kept: %s"
          % str(sorted({(r["pass"], r["position_in_pass"]) for r in all7})[0]))

    print("\nexcluded cells:")
    print("  %-10s %7s %9s %11s %10s %9s" %
          ("pass,pos", "threads", "duration", "threshold", "cell median", "worst"))
    bytag = {}
    for r in all7:
        if r.get("phase") == "decode":
            bytag[(r["pass"], r["position_in_pass"])] = r
    for k in sorted(drop7):
        r = bytag[k]
        print("  %-10s %7d %8ds %10.0fs %10.2f %9.3f"
              % ("%d,%d" % k, r["threads"], dur7[k], thresh7[r["threads"]],
                 r["tok_s_median"], min(r["samples_ts"])))

    kept_dur = [dur7[k] for k in dur7 if k not in drop7]
    print("\nkept-cell durations: min %ds, median %ds, max %ds"
          % (min(kept_dur), st.median(kept_dur), max(kept_dur)))
    kept_nonone = [dur7[k] for k in dur7 if k not in drop7 and thr7[k] > 1]
    print("kept-cell durations excluding t=1: min %ds, median %ds, max %ds"
          % (min(kept_nonone), st.median(kept_nonone), max(kept_nonone)))

    passes_left = collections.defaultdict(set)
    for r in keep7:
        passes_left[r["threads"]].add(r["pass"])
    print("\npasses surviving per thread count:")
    low = []
    for t in sorted(passes_left):
        n = len(passes_left[t])
        flag = "  <-- below four" if n < 5 else ""
        if n < 4:
            low.append(t)
        print("   t=%-3d %d of 5%s" % (t, n, flag))
    print("thread counts left with fewer than FOUR passes: %s"
          % (low if low else "none"))

    by7 = collections.defaultdict(list)
    for r in keep7:
        by7[r["threads"]].extend(r["samples_ts"])
    med7 = {t: st.median(v) for t, v in by7.items()}
    peak7 = max(med7, key=med7.get)
    top7 = max(med7)
    bytes7 = all7[0]["bytes"]

    print("\n%5s %8s %8s %8s %8s %7s %7s"
          % ("t", "median", "p25", "p75", "min", "CV%", "n"))
    for t in sorted(by7):
        v = by7[t]
        print("%5d %8.2f %8.2f %8.2f %8.2f %7.1f %7d"
              % (t, st.median(v), pct(v, 25), pct(v, 75), min(v), cv(v), len(v)))

    roof = BW_CEILING_GBS * 1e9 / bytes7
    print("\npeak %.2f tok/s at t=%d; CV there %.1f%%"
          % (med7[peak7], peak7, cv(by7[peak7])))
    for t in (18, 20):
        if t in by7:
            print("t=%-2d median %.1f%% of peak, p75 %.1f%% of peak, worst %.1f%% "
                  "of peak, CV %.1f%%"
                  % (t, 100 * med7[t] / med7[peak7],
                     100 * pct(by7[t], 75) / med7[peak7],
                     100 * min(by7[t]) / med7[peak7], cv(by7[t])))
    print("roofline: %.1f GB/s / %.3f GB = %.2f tok/s; measured peak is %.0f%% of it"
          % (BW_CEILING_GBS, bytes7 / 1e9, roof, 100 * med7[peak7] / roof))

    put("SevenBytes", "{:,}".format(bytes7).replace(",", "\\,"))
    put("SevenGB", "%.3f" % (bytes7 / 1e9))
    put("SevenCells", str(cells_total))
    put("SevenDropped", str(len(drop7)))
    put("SevenKept", str(cells_total - len(drop7)))
    put("SevenMinPasses", str(min(len(v) for v in passes_left.values())))
    put("SevenMinPassesT", ", ".join(str(t) for t in sorted(passes_left)
                                     if len(passes_left[t]) ==
                                     min(len(v) for v in passes_left.values())))
    put("SevenDurMed", "%d" % st.median(kept_nonone))
    put("SevenDurMin", "%d" % min(kept_nonone))
    put("SevenDurMax", "%d" % max(kept_nonone))
    put("SevenDurOneMed", "%d" % st.median([dur7[k] for k in dur7
                                            if thr7[k] == 1 and k not in drop7]))
    put("SevenPeakT", str(peak7))
    put("SevenPeak", "%.2f" % med7[peak7])
    put("SevenCVPeak", "%.1f" % cv(by7[peak7]))
    put("SevenTopT", str(top7))
    put("SevenCVTop", "%.1f" % cv(by7[top7]))
    put("SevenCVEighteen", "%.1f" % cv(by7[18]))
    put("SevenMedEighteen", "%.1f" % (100 * med7[18] / med7[peak7]))
    put("SevenPSevenFiveEighteen", "%.1f" % (100 * pct(by7[18], 75) / med7[peak7]))
    put("SevenWorstEighteen", "%.1f" % (100 * min(by7[18]) / med7[peak7]))
    put("SevenMedTop", "%.1f" % (100 * med7[top7] / med7[peak7]))
    put("SevenPSevenFiveTop", "%.1f" % (100 * pct(by7[top7], 75) / med7[peak7]))
    put("SevenWorstTop", "%.1f" % (100 * min(by7[top7]) / med7[peak7]))
    put("SevenRoof", "%.2f" % roof)
    put("SevenRoofFrac", "%.0f" % (100 * med7[peak7] / roof))
    put("BWCeil", "%.1f" % BW_CEILING_GBS)
    rows = []
    for t in sorted(by7):
        v = by7[t]
        rows.append("%d & %.2f & %.2f & %.2f & %.2f & %.1f \\\\"
                    % (t, st.median(v), pct(v, 25), pct(v, 75), min(v), cv(v)))
    put("TableSevenB", "%\n" + "\n".join(rows))


    # --------------------------------------------------------------------------
    # 3. The size contrast, 0.5B against 7B under the identical protocol
    # --------------------------------------------------------------------------
    print()
    print("=" * 72)
    print("3. SIZE CONTRAST  (0.5B against 7B, same protocol)")
    print("=" * 72)
    rows05 = load(RAND05)
    drop05, thresh05, dur05, thr05 = stall_excluded(rows05)
    print("\nthe same exclusion rule applied to the 0.5B sweep drops %d cells"
          % len(drop05))
    by05 = collections.defaultdict(list)
    for r in rows05:
        if r.get("phase") != "decode" or "error" in r:
            continue
        if (r["pass"], r["position_in_pass"]) in drop05:
            continue
        by05[r["threads"]].extend(r["samples_ts"])
    med05 = {t: st.median(v) for t, v in by05.items()}
    peak05 = max(med05, key=med05.get)
    top05 = max(med05)
    bytes05 = rows05[0]["bytes"]
    roof05 = BW_CEILING_GBS * 1e9 / bytes05

    cv05_peak, cv05_top = cv(by05[peak05]), cv(by05[top05])
    cv7_peak, cv7_top = cv(by7[peak7]), cv(by7[top7])
    r05 = cv05_top / cv05_peak
    r7 = cv7_top / cv7_peak

    print("\n%-8s %6s %8s %9s %9s %8s %9s %8s"
          % ("model", "GB", "peak t", "peak", "CV peak", "CV t=20", "ratio",
             "% roof"))
    print("%-8s %6.3f %8d %9.2f %8.1f%% %7.1f%% %8.1fx %7.0f%%"
          % ("0.5B", bytes05 / 1e9, peak05, med05[peak05], cv05_peak, cv05_top,
             r05, 100 * med05[peak05] / roof05))
    print("%-8s %6.3f %8d %9.2f %8.1f%% %7.1f%% %8.1fx %7.0f%%"
          % ("7B", bytes7 / 1e9, peak7, med7[peak7], cv7_peak, cv7_top,
             r7, 100 * med7[peak7] / roof))
    print("\nreliability penalty of oversubscription, CV(t=20)/CV(peak):")
    print("   0.5B  %.1f%% -> %.1f%%  = %.1fx" % (cv05_peak, cv05_top, r05))
    print("   7B    %.1f%% -> %.1f%%  = %.1fx" % (cv7_peak, cv7_top, r7))
    print("   the 7B penalty is %.1fx SMALLER than the 0.5B penalty" % (r05 / r7))
    print("median fall from peak to t=20: 0.5B %.1f%%, 7B %.1f%%"
          % (100 * (1 - med05[top05] / med05[peak05]),
             100 * (1 - med7[top7] / med7[peak7])))
    print("worst sample as %% of peak at t=20: 0.5B %.0f%%, 7B %.0f%%"
          % (100 * min(by05[top05]) / med05[peak05],
             100 * min(by7[top7]) / med7[peak7]))

    put("HalfBytes", "%.3f" % (bytes05 / 1e9))
    put("HalfRoof", "%.1f" % roof05)
    put("HalfRoofFrac", "%.0f" % (100 * med05[peak05] / roof05))
    put("HalfPeakT", str(peak05))
    put("HalfPeak", "%.1f" % med05[peak05])
    put("HalfCVPeak", "%.1f" % cv05_peak)
    put("HalfCVTop", "%.1f" % cv05_top)
    put("HalfDropped", str(len(drop05)))
    put("HalfWorstTop", "%.0f" % (100 * min(by05[top05]) / med05[peak05]))
    put("HalfMedianFall", "%.1f" % (100 * (1 - med05[top05] / med05[peak05])))
    put("SevenMedianFall", "%.1f" % (100 * (1 - med7[top7] / med7[peak7])))
    put("RatioHalf", "%.1f" % r05)
    put("RatioSeven", "%.1f" % r7)
    put("RatioOfRatios", "%.1f" % (r05 / r7))
    put("SizeRows", "%\n" + "\n".join([
        "Qwen 0.5B & %.2f & %d & %.1f & %.0f\\%% & %.1f\\%% & %.1f\\%% & %.1f$\\times$ \\\\"
        % (bytes05 / 1e9, peak05, med05[peak05], 100 * med05[peak05] / roof05,
           cv05_peak, cv05_top, r05),
        "Qwen 7.6B & %.2f & %d & %.1f & %.0f\\%% & %.1f\\%% & %.1f\\%% & %.1f$\\times$ \\\\"
        % (bytes7 / 1e9, peak7, med7[peak7], 100 * med7[peak7] / roof,
           cv7_peak, cv7_top, r7)]))


    # --------------------------------------------------------------------------
    # 3b. The same quantities for all five models, as a check on the contrast
    # --------------------------------------------------------------------------
    # The contrast above is between the two extremes of the size range, because
    # they are the two the manuscript reports. The three intermediate models
    # were measured under the same protocol and are in the release, so the
    # honest check is whether they interpolate. They do not, and the paper has
    # to say so rather than let a reader assume a monotone law.
    print()
    print("=" * 72)
    print("3b. ALL FIVE MODELS UNDER THE PROTOCOL")
    print("=" * 72)
    allm = collections.defaultdict(lambda: collections.defaultdict(list))
    nb = {}
    for path in (RAND05, os.path.join(DATA, "randomized_sweep_sizes.jsonl"),
                 RAND7B):
        if not os.path.exists(path):
            continue
        rws = load(path)
        dp, _, _, _ = stall_excluded(rws)
        for r in rws:
            if r.get("phase") != "decode" or "error" in r:
                continue
            if (r["pass"], r["position_in_pass"]) in dp:
                continue
            allm[r["tag"]][r["threads"]].extend(r["samples_ts"])
            nb[r["tag"]] = r["bytes"]
    order = ["qwen0.5b", "llama1.2b", "qwen1.5b", "qwen3b", "qwen7b"]
    print()
    print("%-10s %6s %6s %9s %8s %8s %7s %7s"
          % ("tag", "GB", "t*", "peak", "CV t*", "CV 20", "ratio", "% roof"))
    ratios, roofs = [], []
    for t in order:
        if t not in allm:
            continue
        h = allm[t]
        m = {k: st.median(v) for k, v in h.items()}
        pk = max(m, key=m.get)
        rf = BW_CEILING_GBS * 1e9 / nb[t]
        rat = cv(h[20]) / cv(h[pk])
        ratios.append((nb[t], rat))
        roofs.append((100 * m[pk] / rf, rat))
        print("%-10s %6.2f %6d %9.2f %7.1f%% %7.1f%% %6.1fx %6.0f%%"
              % (t, nb[t] / 1e9, pk, m[pk], cv(h[pk]), cv(h[20]), rat,
                 100 * m[pk] / rf))
    mono = all(ratios[i][1] >= ratios[i + 1][1] for i in range(len(ratios) - 1))
    print()
    print("is the penalty monotone decreasing in model size across all five? %s"
          % ("yes" if mono else "NO"))
    if not mono:
        mid = [r for _, r in ratios[1:]]
        print("   the 0.5B is the extreme case at %.1fx; every model from 1.2B up"
              % ratios[0][1])
        print("   sits between %.1fx and %.1fx with no ordering by size."
              % (min(mid), max(mid)))
        odd = min(roofs[1:], key=lambda z: z[0])
        print("   and the roofline argument does not order them either: the model"
              " at %.0f%% of" % odd[0])
        print("   the ceiling, the furthest below it, has a penalty of %.1fx."
              % odd[1])
    put("AllMono", "yes" if mono else "no")
    put("MidRatioLo", "%.1f" % min(r for _, r in ratios[1:]))
    put("MidRatioHi", "%.1f" % max(r for _, r in ratios[1:]))
    put("OddRoof", "%.0f" % min(roofs[1:], key=lambda z: z[0])[0])
    put("OddRatio", "%.1f" % min(roofs[1:], key=lambda z: z[0])[1])
    put("AllModels", str(len([t for t in order if t in allm])))

    # --------------------------------------------------------------------------
    # 4. Does the paper's two-term model predict the size contrast?
    # --------------------------------------------------------------------------
    print()
    print("=" * 72)
    print("4. DOES THE TWO-TERM MODEL PREDICT THIS?")
    print("=" * 72)
    print("""
    The model in the paper is t(n) = max(B/BW(n), I/(IPC f n)), fitted on the
    Pi for the THREAD OPTIMUM. It is deterministic: it has no contention term and
    no variance term, so it cannot predict a coefficient of variation at all. What
    it does predict is how close each model runs to the streaming term, and that is
    the quantity the interpretation below rests on.""")
    for nm, b, m, rf in (("0.5B", bytes05, med05[peak05], roof05),
                         ("7B", bytes7, med7[peak7], roof)):
        print("   %-5s streaming-term ceiling %6.2f tok/s, measured peak %6.2f, "
              "%3.0f%% of it" % (nm, rf, m, 100 * m / rf))
    print("""
    So the streaming term is nearly binding at 7B and slack at 0.5B, which is the
    premise of the interpretation. The model as published does NOT output a spread,
    so it does not predict the reliability contrast. Reported as an argument, not
    as a model result.""")

    open(OUT, "w").write("\n".join(lines) + "\n")
    print()
    print("wrote", OUT, "(%d macros)" % (len(lines) - 1))


if __name__ == "__main__":
    main()
