#!/usr/bin/env python3
"""Laptop macros, from the randomised protocol only.

Replaces code/fill_laptop.py, which read the sequential sweeps. Those are not
usable: thread count was confounded with elapsed time in every one of them, the
same configuration produced falls of 15.2, 35.1, 49.8, 55.4 and 61.4 percent
depending on when each cell happened to be measured, and a session's reference
cell moved 14.3% on identical work.

Under the randomised protocol the same position check gives +2.4% across fifteen
positions, so these numbers are comparable to each other.

It also reports the distribution rather than a median per cell, because the
median is the wrong summary here. Past the knee the samples are bimodal: at
eighteen threads the upper quartile is 95% of the peak's upper quartile while
the minimum is 36% of the peak. Throughput does not fall so much as become
unreliable, and a table of medians hides exactly that.

Reads data/randomized_sweep.jsonl (the 0.5B model), data/randomized_sweep_sizes.jsonl
(the 1.2B, 1.5B and 3B sweeps) and data/randomized_sweep_7b.jsonl (the 7B, which
shipped separately as two shards). The size-scaling macros are only emitted once
every model has been measured this way; a law derived from one clean curve and
four confounded ones is not a law.

Every file is put through the stall exclusion of code/analyze_headroom_sizes.py
before anything is computed, so these macros, the tables built from them and
Fig. 1 all describe the same set of cells. The 0.5B sweep loses none.

Outputs paper/numbers_laptop.tex.
"""
import collections
import json
import os
import statistics as st
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(HERE, "code"))
from analyze_headroom_sizes import stall_excluded          # noqa: E402

SRC = os.path.join(HERE, "data", "randomized_sweep.jsonl")
SIZES = [os.path.join(HERE, "data", "randomized_sweep_sizes.jsonl"),
         os.path.join(HERE, "data", "randomized_sweep_7b.jsonl")]
OUT = os.path.join(HERE, "paper", "numbers_laptop.tex")

PCORES = 6
LOGICAL = 20
LABEL = {"qwen0.5b": "Qwen 0.5B", "llama1.2b": "Llama 1.2B",
         "qwen1.5b": "Qwen 1.5B", "qwen3b": "Qwen 3.1B", "qwen7b": "Qwen 7.6B"}
ORDER = ["qwen0.5b", "llama1.2b", "qwen1.5b", "qwen3b", "qwen7b"]
COLS = [1, 4, 6, 8, 12, 16, 20]

lines = ["% generated by code/fill_laptop_rand.py -- do not edit"]


def put(name, val):
    lines.append(r"\newcommand{\np%s}{%s}" % (name, val))


def pct(vals, p):
    s = sorted(vals)
    k = (len(s) - 1) * p / 100.0
    lo, hi = int(k), min(int(k) + 1, len(s) - 1)
    return s[lo] + (s[hi] - s[lo]) * (k - lo)


def load(path):
    d = collections.defaultdict(lambda: collections.defaultdict(list))
    meta, pos = {}, collections.defaultdict(list)
    if not os.path.exists(path):
        return d, meta, pos
    rows = [json.loads(l) for l in open(path) if l.strip()]
    drop, _, _, _ = stall_excluded(rows)
    for r in rows:
        if "error" in r or r.get("phase") != "decode":
            continue
        if (r["pass"], r["position_in_pass"]) in drop:
            continue
        d[r["tag"]][r["threads"]].extend(r["samples_ts"])
        meta[r["tag"]] = r
        for v in r["samples_ts"]:
            pos[(r["tag"], r["position_in_pass"])].append(v)
    return d, meta, pos


d, meta, pos = load(SRC)
for path in SIZES:
    d2, meta2, pos2 = load(path)
    for t in d2:
        for th in d2[t]:
            d[t][th].extend(d2[t][th])
    meta.update(meta2)
    pos.update(pos2)

if "qwen0.5b" not in d:
    raise SystemExit("no randomised 0.5B data in %s" % SRC)

tags = [t for t in ORDER if t in d]
put("LapRandModels", str(len(tags)))
put("LapRandPasses", str(len({r["pass"] for r in
                              [json.loads(l) for l in open(SRC) if l.strip()]
                              if "pass" in r})))
put("LapLogical", str(LOGICAL))
put("LapPCores", str(PCORES))

# ---- the headline model, in distributional form ----
h = d["qwen0.5b"]
med = {t: st.median(v) for t, v in h.items()}
peak_t = max(med, key=med.get)
top = max(med)
put("LapPeakT", str(peak_t))
put("LapPeak", "%.1f" % med[peak_t])
put("LapAtTop", "%.1f" % med[top])
put("LapTopT", str(top))
put("LapMedianFall", "%.1f" % (100 * (1 - med[top] / med[peak_t])))
put("LapAtPCores", "%.1f" % med[PCORES])
put("LapRuleCost", "%.1f" % (100 * (1 - med[PCORES] / med[peak_t])))


def cv(v):
    return 100 * st.pstdev(v) / st.mean(v)


put("LapCVPeak", "%.1f" % cv(h[peak_t]))
put("LapCVTop", "%.1f" % cv(h[top]))
put("LapCVEighteen", "%.1f" % cv(h[18]) if 18 in h else "n/a")
put("LapPFiveTop", "%.0f" % (100 * pct(h[top], 75) / pct(h[peak_t], 75)))
put("LapPFiveEighteen", "%.0f" % (100 * pct(h[18], 75) / pct(h[peak_t], 75)))
put("LapWorstTop", "%.0f" % (100 * min(h[top]) / med[peak_t]))
put("LapWorstEighteen", "%.0f" % (100 * min(h[18]) / med[peak_t]))

rows = []
for t in sorted(h):
    v = h[t]
    rows.append("%d & %.1f & %.1f & %.1f & %.1f & %.1f \\\\"
                % (t, st.median(v), pct(v, 25), pct(v, 75), min(v), cv(v)))
put("TableLapRand", "%\n" + "\n".join(rows))

# ---- drift, normalised within thread count so position is the only variable ----
res = collections.defaultdict(list)
for (tag, p), vals in pos.items():
    if tag != "qwen0.5b":
        continue
    for v in vals:
        pass
for line in open(SRC):
    if not line.strip():
        continue
    r = json.loads(line)
    if "error" in r or r.get("phase") != "decode":
        continue
    m = st.median(h[r["threads"]])
    for v in r["samples_ts"]:
        res[r["position_in_pass"]].append(v / m)
xs = sorted(res)
ys = [st.median(res[p]) for p in xs]
mx, my = st.mean(map(float, xs)), st.mean(ys)
den = sum((float(x) - mx) ** 2 for x in xs)
slope = sum((float(x) - mx) * (y - my) for x, y in zip(xs, ys)) / den if den else 0
put("LapPosDrift", "%.1f" % abs(100 * slope * (max(xs) - min(xs))))
put("LapSeqDrift", "14.3")          # measured by order_control.sh, for contrast

# ---- size scaling, only when every model has been measured this way ----
complete = [t for t in ORDER if t in d and len(d[t]) >= 10]
put("LapSizeModels", str(len(complete)))
if len(complete) == len(ORDER):
    srows = []
    for t in complete:
        m = {th: st.median(v) for th, v in d[t].items()}
        pkt = max(m, key=m.get)
        srows.append("%s & %d & %.1f & %.1f & %.1f\\%% & %.1f \\\\"
                     % (LABEL[t], pkt, m[pkt], m[max(m)],
                        100 * (1 - m[max(m)] / m[pkt]), cv(d[t][max(m)])))
    put("TableLapSizes", "%\n" + "\n".join(srows))
    put("LapSizeReady", "1")
else:
    put("LapSizeReady", "0")


# ---- prefill, from the same randomised passes ----
# The randomised sweep records both phases, so prefill gets the same treatment
# as decode rather than being carried over from the confounded sequential runs.
pre = collections.defaultdict(list)
for line in open(SRC):
    if not line.strip():
        continue
    r = json.loads(line)
    if "error" in r or r.get("phase") != "prefill":
        continue
    pre[r["threads"]].extend(r["samples_ts"])
if pre:
    prows = []
    for th in sorted(pre):
        v = pre[th]
        prows.append("%d & %.1f & %.1f & %.1f \\\\"
                     % (th, st.median(v), min(v), cv(v)))
    put("TableLapPrefill", "%\n" + "\n".join(prows))
    lo, hi = min(pre), max(pre)
    put("LapPreLo", "%.1f" % st.median(pre[lo]))
    put("LapPreHi", "%.1f" % st.median(pre[hi]))
    put("LapPreScale", "%.1f" % (st.median(pre[hi]) / st.median(pre[lo])))
    put("LapPrePeakT", str(max(pre, key=lambda k: st.median(pre[k]))))
    put("LapPreCVMax", "%.1f" % max(cv(v) for v in pre.values()))

open(OUT, "w").write("\n".join(lines) + "\n")
print("wrote", OUT, "(%d macros)" % (len(lines) - 1))
print("  peak %.1f at t=%d ; t=%d %.1f ; median fall %.1f%%"
      % (med[peak_t], peak_t, top, med[top], 100 * (1 - med[top] / med[peak_t])))
print("  P-core rule costs %.1f%%" % (100 * (1 - med[PCORES] / med[peak_t])))
print("  CV: %.1f%% at peak, %.1f%% at t=%d" % (cv(h[peak_t]), cv(h[top]), top))
print("  position drift %.1f%% (sequential was 14.3%%)" % abs(100 * slope * (max(xs) - min(xs))))
print("  models measured under this protocol: %d of %d" % (len(complete), len(ORDER)))
