#!/usr/bin/env python3
"""Paper 17's laptop tables and figure, from one source of truth.

WHY THIS REPLACES HAND-MAINTAINED NUMBERS. Three defects in the submitted
version all trace to the laptop numbers living in three places at once:

  * Table tab:decode printed 86.4 for the 0.5B model at 8 threads,
    code/gen_fig_cliff.py hardcoded 90.2 for the same cell, and CAL's referees
    noticed the text and the figure disagreeing.
  * The manuscript promised medians at 8 threads and printed a maximum for the
    1.5B cell (TABLE_AUDIT_2026-09-17.md).
  * The Llama 1.2B row had no released records at all.

Everything the manuscript says about the laptop is now generated from
data/laptop_sweep.jsonl, so the table, the figure and the prose cannot drift
apart: there is nowhere for them to drift to.

Outputs paper/numbers_laptop.tex and, with --fig, paper/fig_cliff.pdf.
"""
import argparse
import collections
import json
import os
import statistics as st

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(HERE, "data", "laptop_sweep.jsonl")
PI = os.path.join(HERE, "data", "pi_decode_control.jsonl")
OUT = os.path.join(HERE, "paper", "numbers_laptop.tex")
FIG = os.path.join(HERE, "paper", "fig_cliff.pdf")

# Display name and ordering; params come from the records themselves.
LABEL = {"qwen0.5b": "Qwen 0.5B", "llama1.2b": "Llama 1.2B",
         "qwen1.5b": "Qwen 1.5B", "qwen3b": "Qwen 3.1B", "qwen7b": "Qwen 7.6B"}
ORDER = ["qwen0.5b", "llama1.2b", "qwen1.5b", "qwen3b", "qwen7b"]
# Columns printed in the manuscript tables. The sweep measures more thread
# counts than fit in a table; the figure uses all of them.
COLS = [1, 4, 6, 7, 8, 14, 20]
PCORES = 6

lines = ["% generated by code/fill_laptop.py -- do not edit"]


def put(name, val):
    lines.append(r"\newcommand{\np%s}{%s}" % (name, val))


def load():
    d = collections.defaultdict(lambda: collections.defaultdict(dict))
    meta = {}
    for line in open(SRC):
        if not line.strip():
            continue
        r = json.loads(line)
        if "error" in r or r.get("arm") != "default":
            continue
        d[r["tag"]][r["phase"]][r["threads"]] = r
        meta[r["tag"]] = r
    return d, meta


def stat(r):
    """The median of the samples, always. The manuscript says median; this is
    the only place that decides what that means, so it cannot disagree."""
    s = r.get("samples_ts")
    return st.median(s) if s else r["tok_s_mean"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fig", action="store_true")
    args = ap.parse_args()

    d, meta = load()
    tags = [t for t in ORDER if t in d]
    if not tags:
        raise SystemExit("no laptop records in %s" % SRC)

    reps = {r["reps"] for t in tags for ph in d[t].values() for r in ph.values()}
    put("LapReps", str(min(reps)))
    put("LapNThreads", str(len(d[tags[0]]["decode"])))
    put("LapNModels", str(len(tags)))
    put("LapBuild", str(meta[tags[0]].get("build") or "unknown"))

    dec_rows, pre_rows, drops = [], [], {}
    for t in tags:
        dec = {th: stat(r) for th, r in d[t]["decode"].items()}
        pre = {th: stat(r) for th, r in d[t]["prefill"].items()}
        peak_t = max(dec, key=dec.get)
        drop = 100 * (1 - dec[max(dec)] / dec[peak_t])
        drops[t] = (drop, peak_t, dec, pre)

        def cell(v, th, bold):
            x = v.get(th)
            if x is None:
                return "--"
            s = "%.1f" % x
            return "\\textbf{%s}" % s if bold else s

        dec_rows.append("%s & %s & %s \\\\" % (
            LABEL[t],
            " & ".join(cell(dec, th, th == peak_t) for th in COLS),
            "\\textbf{%.1f\\%%}" % drop))
        scale = pre[max(pre)] / pre[min(pre)]
        pre_rows.append("%s & %s & %.1f$\\times$ \\\\" % (
            LABEL[t],
            " & ".join(cell(pre, th, False) for th in COLS),
            scale))

        short = LABEL[t].split()[-1].replace(".", "").replace("B", "")
        key = {"05": "Half", "12": "OneTwo", "15": "OneFive",
               "31": "ThreeOne", "76": "SevenSix"}.get(short, short)
        put("Lap%sPeakT" % key, str(peak_t))
        put("Lap%sPeak" % key, "%.1f" % dec[peak_t])
        put("Lap%sAt20" % key, "%.1f" % dec[max(dec)])
        put("Lap%sDrop" % key, "%.1f" % drop)
        # Spread at the peak, which is what the referees asked to see.
        s = d[t]["decode"][peak_t].get("samples_ts") or []
        if len(s) > 1:
            put("Lap%sPeakSpread" % key, "%.1f" % (100 * (max(s) - min(s)) / st.median(s)))

    put("TableDecode", "%\n" + "\n".join(dec_rows))
    put("TablePrefill", "%\n" + "\n".join(pre_rows))
    put("LapCols", " & ".join("\\textbf{t=%d}" % c for c in COLS))

    dmin = min(v[0] for v in drops.values())
    dmax = max(v[0] for v in drops.values())
    put("LapDropMin", "%.1f" % dmin)
    put("LapDropMax", "%.1f" % dmax)
    # The deployment claim is about models below the crossover, so it excludes
    # the largest model rather than quoting a range the table contradicts.
    sub = [drops[t][0] for t in tags if t != "qwen7b"]
    put("LapSubDropMin", "%.0f" % min(sub))
    put("LapSubDropMax", "%.0f" % max(sub))
    put("LapPeakAtOrBelowP",
        str(sum(1 for t in tags if drops[t][1] <= PCORES)))

    open(OUT, "w").write("\n".join(lines) + "\n")
    print("wrote", OUT, "(%d macros)" % (len(lines) - 1))
    for t in tags:
        drop, peak_t, dec, _ = drops[t]
        print("  %-10s peak t=%-2d %6.1f tok/s -> %6.1f at t=%d  drop %.1f%%"
              % (LABEL[t], peak_t, dec[peak_t], dec[max(dec)], max(dec), drop))

    if args.fig:
        make_fig(tags, drops)


def make_fig(tags, drops):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    matplotlib.rcParams["pdf.fonttype"] = 42      # no Type-3, per venue rules
    matplotlib.rcParams["ps.fonttype"] = 42
    matplotlib.rcParams["font.size"] = 9

    pi = collections.defaultdict(dict)
    NAME = {"qwen0.5b-q4km.gguf": "Qwen 0.5B", "llama1b-q4km.gguf": "Llama 1.2B",
            "qwen1.5b-q4km.gguf": "Qwen 1.5B"}
    for line in open(PI):
        r = json.loads(line)
        if r["model"] in NAME:
            pi[NAME[r["model"]]][r["threads"]] = r["decode_tps"]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(7.0, 2.7),
                                   gridspec_kw={"width_ratios": [1.6, 1]})
    for (t, mk) in zip(tags, ["o", "s", "^", "D", "v"]):
        dec = drops[t][2]
        ts = sorted(dec)
        peak = max(dec.values())
        ax1.plot(ts, [100 * dec[x] / peak for x in ts], marker=mk, markersize=3.5,
                 label=LABEL[t], linewidth=1.3)
    ax1.axvline(PCORES, color="0.5", linestyle="--", linewidth=1)
    ax1.text(PCORES + 0.25, 58, "6 P-cores", rotation=90, va="bottom", ha="left",
             fontsize=7.5, color="0.35")
    ax1.set_xlabel("threads")
    ax1.set_ylabel("decode, % of peak")
    ax1.set_title("i7-12700H (6P + 8E)", fontsize=9)
    ax1.legend(fontsize=6.5, loc="lower left", frameon=False)
    ax1.grid(alpha=0.3, linewidth=0.5)

    for name, mk in zip(["Qwen 0.5B", "Llama 1.2B", "Qwen 1.5B"], ["o", "s", "^"]):
        if name not in pi:
            continue
        v = pi[name]
        ts = sorted(v)
        peak = max(v.values())
        ax2.plot(ts, [100 * v[x] / peak for x in ts], marker=mk, markersize=3.5,
                 label=name, linewidth=1.3)
    ax2.set_xlabel("threads")
    ax2.set_title("Pi 5 (4 identical A76)", fontsize=9)
    ax2.set_xticks([1, 2, 3, 4])
    ax2.legend(fontsize=6.5, loc="lower left", frameon=False)
    ax2.grid(alpha=0.3, linewidth=0.5)

    fig.tight_layout()
    fig.savefig(FIG)
    print("wrote", FIG)


if __name__ == "__main__":
    main()
