#!/usr/bin/env python3
"""Energy macros for Paper 17, from data the manuscript never used.

data/homo_sweep.jsonl carries mean package power and energy per token for all 36
decode measurements, and the paper mentions energy once. The question a decode
paper should ask of it: is the thread count that maximises throughput also the
one that minimises energy per token? On homogeneous cores it usually is not.

Outputs paper/numbers_energy.tex.
"""
import collections
import json
import os
import statistics as st

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(HERE, "data", "homo_sweep.jsonl")
# The two artifacts added with the counter campaign (F16 and Q5_0) carry the
# same power passes, so they belong in this analysis too. Keeping the artifact
# set identical to the mechanism section's is not cosmetic: the two sections
# argue about the same eleven thread curves and must not disagree on how many.
ADD = os.path.join(HERE, "data", "homo_sweep_add.jsonl")
OUT = os.path.join(HERE, "paper", "numbers_energy.tex")

lines = ["% generated by code/fill_energy.py -- do not edit"]


def put(name, val):
    lines.append(r"\newcommand{\np%s}{%s}" % (name, val))


d = collections.defaultdict(dict)
for path in (SRC, ADD):
    for line in open(path):
        if not line.strip():
            continue
        r = json.loads(line)
        if r["phase"] == "decode":
            d[(r["params_B"], r["tag"])][r["threads"]] = r

full = {k: v for k, v in d.items()
        if len(v) == 4 and all(v[t].get("mJ_per_tok") for t in v)}

# Does fastest == cheapest?
agree, pen, rows = 0, [], []
for k, v in sorted(full.items(), key=lambda x: (x[0][0], x[0][1])):
    tp = {t: v[t]["tok_s"] for t in v}
    en = {t: v[t]["mJ_per_tok"] for t in v}
    ft, ct = max(tp, key=tp.get), min(en, key=en.get)
    p = 100 * (en[ft] / en[ct] - 1)
    agree += (ft == ct)
    pen.append(p)
    rows.append("%s %s & %d & %.1f & %d & %.0f & %s \\\\" % (
        ("%.1f" % k[0]).rstrip("0").rstrip(".") + "\\,B",
        k[1].replace("_", "\\_"), ft, tp[ft], ct, en[ct],
        "--" if ft == ct else "%.1f\\%%" % p))
put("TableEnergy", "%\n" + "\n".join(rows))
put("EnAgree", str(agree))
put("EnTotal", str(len(full)))
put("EnDisagree", str(len(full) - agree))
# Two different means, and the manuscript must not confuse them: the penalty
# averaged over every artifact (four of which pay nothing) is not the penalty
# paid by the artifacts whose optima actually disagree.
nz = [p for p in pen if p > 0]
put("EnPenMean", "%.1f" % st.mean(pen))
put("EnPenMeanDis", "%.1f" % st.mean(nz))
put("EnPenMax", "%.1f" % max(pen))

# The mechanism: power scales faster than throughput.
W = {1: "One", 2: "Two", 3: "Three", 4: "Four"}
by_t = {}
for t in (1, 2, 3, 4):
    by_t[t] = dict(
        W=st.mean([v[t]["mean_W"] for v in full.values()]),
        T=st.mean([v[t]["tok_s"] for v in full.values()]),
        E=st.mean([v[t]["mJ_per_tok"] for v in full.values()]))
    put("EnW%s" % W[t], "%.2f" % by_t[t]["W"])
    put("EnT%s" % W[t], "%.1f" % by_t[t]["T"])
    put("EnE%s" % W[t], "%.0f" % by_t[t]["E"])
put("EnPowerRise", "%.0f" % (100 * (by_t[4]["W"] / by_t[1]["W"] - 1)))
put("EnTputRise", "%.0f" % (100 * (by_t[4]["T"] / by_t[1]["T"] - 1)))
best = min(by_t, key=lambda t: by_t[t]["E"])
put("EnBestThreads", str(best))
put("EnWorstPenalty", "%.0f" % (100 * (by_t[4]["E"] / by_t[best]["E"] - 1)))

open(OUT, "w").write("\n".join(lines) + "\n")
print("wrote", OUT, "(%d macros)" % (len(lines) - 1))
print("  fastest == cheapest in %d of %d artifacts" % (agree, len(full)))
print("  1->4 threads: power +%.0f%%, throughput +%.0f%%"
      % (100 * (by_t[4]["W"] / by_t[1]["W"] - 1), 100 * (by_t[4]["T"] / by_t[1]["T"] - 1)))
print("  energy-optimal thread count on average: %d" % best)
