#!/usr/bin/env python3
"""Paper 17's homogeneous-core mechanism table, on matched artifacts.

WHAT CHANGED. The previous version of this table paired a thread curve measured
on official published GGUFs against instructions-per-token measured on locally
requantized files, at different llama-bench settings. Paper 16 established that
those requantized files are not the same artifacts (290 tensors against the
canonical 291, because the requantized graph ties the embedding to the output
head), and perf over a whole bench process charges model load and prefill to the
token count, with an overhead that scales with file size, which is the variable
under test. Both mismatches are gone here: counters come from the same official
GGUF the thread curve used, verified by sha256, and they are differential,
(I_256 - I_128) / tokens, so every fixed cost cancels.

The differential also validates the old numbers rather than discarding them. On
the six formats both methods cover the two agree at r=+1.00 and differ by at
most 7%, four of the six lower, as removing a fixed overhead predicts.

Outputs paper/numbers_mech.tex.
"""
import collections
import json
import math
import os
import statistics as st

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PERF = os.path.join(HERE, "data", "homo_perf.jsonl")
SWEEP = os.path.join(HERE, "data", "homo_sweep.jsonl")
ADD = os.path.join(HERE, "data", "homo_sweep_add.jsonl")
# The 1.5B family extension: four more artifacts at that parameter count, run
# so the decline-versus-instructions relationship can be tested WITHIN the
# 1.5B family instead of rested on the two points that were there before.
PERF15 = os.path.join(HERE, "data", "homo_perf_15b.jsonl")
ADD15 = os.path.join(HERE, "data", "homo_sweep_add_15b.jsonl")
# A THIRD family, and a different architecture: Llama-3.2-1B in five formats.
# The two Qwen2 families could share a quirk of that architecture; a third
# family from another model line tests whether the relationship is about
# kernels or about Qwen.
PERFLL = os.path.join(HERE, "data", "homo_perf_llama.jsonl")
ADDLL = os.path.join(HERE, "data", "homo_sweep_add_llama.jsonl")
OUT = os.path.join(HERE, "paper", "numbers_mech.tex")

lines = ["% generated by code/fill_mech.py -- do not edit"]


def put(name, val):
    lines.append(r"\newcommand{\np%s}{%s}" % (name, val))


def pearson(x, y):
    n = len(x)
    mx, my = st.mean(x), st.mean(y)
    sx = math.sqrt(sum((a - mx) ** 2 for a in x))
    sy = math.sqrt(sum((b - my) ** 2 for b in y))
    if not sx or not sy:
        return float("nan")
    return sum((a - mx) * (b - my) for a, b in zip(x, y)) / (sx * sy)


# --- thread curves, official sweep plus the two artifacts added with it ---
curve = collections.defaultdict(dict)
for path in (SWEEP, ADD, ADD15, ADDLL):
    for line in open(path):
        if not line.strip():
            continue
        r = json.loads(line)
        if r.get("phase") == "decode":
            curve[(r["params_B"], r["tag"])][r["threads"]] = r

# --- differential counters, keyed the same way ---
perf = {}
for line in [l for f in (PERF, PERF15, PERFLL) for l in open(f)]:
    if not line.strip():
        continue
    r = json.loads(line)
    if "inst_per_token" in r:
        perf[(r["params_B"], r["tag"])] = r

rows, recs = [], []
for k in sorted(perf, key=lambda k: (k[0], perf[k]["inst_per_token"])):
    v = curve.get(k)
    if not v or len(v) < 4:
        continue
    p = perf[k]
    # sha256 must match, or the counters describe a different file
    shas = {r.get("sha256") for r in v.values()} | {p.get("sha256")}
    matched = len(shas) == 1 and None not in shas
    tp = {t: v[t]["tok_s"] for t in v}
    peak = max(tp, key=tp.get)
    decline = 100 * (1 - tp[4] / tp[peak])
    recs.append(dict(params=k[0], tag=k[1], inst=p["inst_per_token"],
                     ipc=p["ipc_decode"], miss=p.get("cache_misses_per_token"),
                     bytes=p["bytes"], peak=peak, decline=decline,
                     matched=matched))
    rows.append("%s %s & %.3f & %.2f & \\textbf{%d} & %.1f\\%% \\\\" % (
        ("%.1f" % k[0]).rstrip("0").rstrip(".") + "\\,B",
        k[1].replace("_", "\\_"), p["inst_per_token"] / 1e9,
        p["ipc_decode"], peak, decline))

put("TableMech", "%\n" + "\n".join(rows))
put("MechN", str(len(recs)))
put("MechMatched", str(sum(r["matched"] for r in recs)))

inst = [r["inst"] for r in recs]
peak = [float(r["peak"]) for r in recs]
dec = [r["decline"] for r in recs]
byt = [float(r["bytes"]) for r in recs]
miss = [float(r["miss"]) for r in recs]


def rr(name, a, b):
    v = pearson(a, b)
    put(name, "%+.2f" % v)
    return v


r_peak = rr("MechRPeak", inst, peak)
r_dec = rr("MechRDecline", inst, dec)
r_byte_peak = rr("MechRBytePeak", byt, peak)
r_byte_dec = rr("MechRByteDecline", byt, dec)
r_miss_dec = rr("MechRMissDecline", miss, dec)

# The 0.5B family alone: parameter count held exactly fixed, so only the
# artifact's kernel varies. This is the clean within-family test.
fam = [r for r in recs if r["params"] == 0.5]
put("MechFamN", str(len(fam)))
rr("MechFamRPeak", [r["inst"] for r in fam], [float(r["peak"]) for r in fam])
rr("MechFamRDecline", [r["inst"] for r in fam], [r["decline"] for r in fam])
rr("MechFamRBytePeak", [float(r["bytes"]) for r in fam], [float(r["peak"]) for r in fam])
rr("MechFamRByteDecline", [float(r["bytes"]) for r in fam], [r["decline"] for r in fam])

# The 1.5B family, now that it has enough members to test on its own.
fam15 = [r for r in recs if r["params"] == 1.5]
put("MechFifN", str(len(fam15)))
if len(fam15) >= 4:
    rr("MechFifRPeak", [r["inst"] for r in fam15], [float(r["peak"]) for r in fam15])
    rr("MechFifRDecline", [r["inst"] for r in fam15], [r["decline"] for r in fam15])
    rr("MechFifRBytePeak", [float(r["bytes"]) for r in fam15], [float(r["peak"]) for r in fam15])
    rr("MechFifRByteDecline", [float(r["bytes"]) for r in fam15], [r["decline"] for r in fam15])

# The Llama family: a third parameter count AND a different architecture.
famll = [r for r in recs if abs(r["params"] - 1.24) < 0.01]
put("MechLlaN", str(len(famll)))
if len(famll) >= 4:
    rr("MechLlaRPeak", [r["inst"] for r in famll], [float(r["peak"]) for r in famll])
    rr("MechLlaRDecline", [r["inst"] for r in famll], [r["decline"] for r in famll])
    rr("MechLlaRBytePeak", [float(r["bytes"]) for r in famll], [float(r["peak"]) for r in famll])
    rr("MechLlaRByteDecline", [float(r["bytes"]) for r in famll], [r["decline"] for r in famll])

# Extremes, named in the prose.
lo = min(recs, key=lambda r: r["inst"])
hi = max(recs, key=lambda r: r["inst"])
for tag, r in (("Lo", lo), ("Hi", hi)):
    put("Mech%sTag" % tag, r["tag"].replace("_", r"\_"))
    put("Mech%sInst" % tag, "%.3f" % (r["inst"] / 1e9))
    put("Mech%sIPC" % tag, "%.2f" % r["ipc"])
    put("Mech%sPeak" % tag, str(r["peak"]))
    put("Mech%sDecline" % tag, "%.1f" % r["decline"])

# F16 is the argument against a pure bytes story, so name it explicitly.
f16 = [r for r in recs if r["tag"] == "F16"]
if f16:
    f = f16[0]
    put("MechFSixteenBytes", "%.2f" % (f["bytes"] / 1e9))
    put("MechFSixteenInst", "%.3f" % (f["inst"] / 1e9))
    put("MechFSixteenPeak", str(f["peak"]))
    put("MechFSixteenDecline", "%.1f" % f["decline"])
    heavier = [r for r in recs if r["bytes"] < f["bytes"] and r["decline"] > f["decline"]]
    put("MechFSixteenBeaten", str(len(heavier)))

# --- Controlled comparisons, because bytes and instructions are confounded ---
# Within a model family the heavy-byte formats are also the light-instruction
# ones (less unpacking work per byte moved), so bytes and instructions run
# anti-correlated and no single r can separate them. These pairs can: each holds
# one of the two roughly fixed and lets the other move.


def rec(tag, params=0.5):
    for r in recs:
        if r["tag"] == tag and r["params"] == params:
            return r
    return None


def pair(name, heavy, light):
    """heavy/light named for BYTES. Records the ratio and both behaviours."""
    a, b = rec(heavy), rec(light)
    if not a or not b:
        return
    put("Pair%sBigTag" % name, a["tag"].replace("_", r"\_"))
    put("Pair%sSmallTag" % name, b["tag"].replace("_", r"\_"))
    put("Pair%sByteRatio" % name, "%.2f" % (a["bytes"] / b["bytes"]))
    put("Pair%sInstRatio" % name, "%.2f" % (a["inst"] / b["inst"]))
    put("Pair%sBigDecline" % name, "%.1f" % a["decline"])
    put("Pair%sSmallDecline" % name, "%.1f" % b["decline"])
    put("Pair%sBigPeak" % name, str(a["peak"]))
    put("Pair%sSmallPeak" % name, str(b["peak"]))
    put("Pair%sBigMB" % name, "%.0f" % (a["bytes"] / 1e6))
    put("Pair%sSmallMB" % name, "%.0f" % (b["bytes"] / 1e6))


# Bytes tripled, instructions barely moved: does behaviour follow bytes?
pair("Bytes", "F16", "Q4_0")
# Bytes nearly equal, instructions tripled: does behaviour follow instructions?
pair("Inst", "Q5_0", "Q4_0")

# The strongest single statement: artifacts that stream MORE bytes but decline
# LESS. A pure saturation account cannot produce one of these.
wrong_sign = 0
for a in recs:
    for b in recs:
        if a["bytes"] > b["bytes"] * 1.1 and a["decline"] < b["decline"] - 1.0:
            wrong_sign += 1
            break
put("MechWrongSign", str(wrong_sign))

# Cross-validation against the requantized counters the previous table used.
OLD = {"Q8_0": 0.140, "Q4_0": 0.158, "Q6_K": 0.183, "Q3_K_M": 0.194,
       "Q2_K": 0.240, "Q4_K_M": 0.439}
pairs = [(OLD[r["tag"]], r["inst"] / 1e9) for r in fam if r["tag"] in OLD]
put("MechXvalN", str(len(pairs)))
put("MechXvalR", "%+.2f" % pearson([a for a, _ in pairs], [b for _, b in pairs]))
put("MechXvalMaxDelta", "%.0f" % max(100 * abs(b - a) / a for a, b in pairs))
put("MechXvalLowerOf", str(sum(1 for a, b in pairs if b < a)))

open(OUT, "w").write("\n".join(lines) + "\n")
print("wrote", OUT, "(%d macros)" % (len(lines) - 1))
print("  artifacts with matched counters + curve: %d (sha-verified %d)"
      % (len(recs), sum(r["matched"] for r in recs)))
print("  peak thread vs inst/tok      r=%+.2f" % r_peak)
print("  4-thread decline vs inst/tok r=%+.2f" % r_dec)
print("  peak thread vs bytes         r=%+.2f" % r_byte_peak)
print("  decline vs bytes             r=%+.2f" % r_byte_dec)
print("  decline vs cache misses/tok  r=%+.2f" % r_miss_dec)
for r in recs:
    print("   %-8s %.1fB inst=%.3fG ipc=%.2f peak=t%d decline=%.1f%% matched=%s"
          % (r["tag"], r["params"], r["inst"] / 1e9, r["ipc"], r["peak"],
             r["decline"], r["matched"]))
